swagger: "2.0"
info:
  title: "Swagger GashNetPlus"
  version: "1.0.0"
  description: "This is the GashNetPlus REST API. The basepath URL is unique for each customer and access is restricted with a Token authorisation. Every succesfull request will return data in JSON format. All query parameters are required but are allowed to be empty."
  contact:
    email: "helpdesk@gashnetplus.be"
basePath: "/v2"
schemes:
- "https"
paths:
  /Entity/List:
    get:
      tags:
      - "Entity"
      summary: "Get entity IDs"
      description: ""
      operationId: "GetEntityList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "dateModified"
        in: "query"
        description: "Only return entity IDs where a change was made after the given date (example: 20220101 -> yyyyMMdd)"
        required: true
        type: "string"
        format: "date"
      - name: "pandStateCodeID"
        in: "query"
        description: "Only return entity IDs with this pand state code ID (example: 10)"
        required: true
        type: "integer"
        format: "int32"
      - name: "attributeCodeID"
        in: "query"
        description: "Only return entity IDs with this attribute code ID (example: 10) (combines with attributeValue)"
        required: true
        type: "integer"
        format: "int32"
      - name: "attributeValue"
        in: "query"
        description: "Only return entity IDs with this attribute value (example: 123456789) (combines with attributeValue)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "integer"
              format: "int32"
      security:
      - bearerAuth: []
  /Entity/Range:
    get:
      tags:
      - "Entity"
      summary: "Get entity data in range (restricted to 100 records/request)"
      description: ""
      operationId: "GetEntityRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "query"
        description: "range of IDs (example: 1,2,3,4,5)"
        required: true
        type: "string"
      - name: "adres"
        in: "query"
        description: "To request adres data or not (example: 0 or 1)"
        required: true
        type: "string"
      - name: "state"
        in: "query"
        description: "To request state data or not (example: 0 or 1)"
        required: true
        type: "string"
      - name: "attributes"
        in: "query"
        description: "To request attribute data or not (example: 0 or 1)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Entity"
      security:
      - bearerAuth: []
  /Complex/List:
    get:
      tags:
      - "Complex"
      summary: "Get complex IDs"
      description: ""
      operationId: "GetComplexList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "dateModified"
        in: "query"
        description: "Only return complex IDs where a change was made after the given date (example: 20220101 -> yyyyMMdd)"
        required: true
        type: "string"
        format: "date"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "integer"
              format: "int32"
      security:
      - bearerAuth: []
  /Complex/Range:
    get:
      tags:
      - "Complex"
      summary: "Get complex data in range (restricted to 100 records/request)"
      description: ""
      operationId: "GetComplexRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "query"
        description: "range of IDs (example: 1,2,3,4,5)"
        required: true
        type: "string"
      - name: "adres"
        in: "query"
        description: "To request adres data or not (example: 0 or 1)"
        required: true
        type: "string"
      - name: "entityList"
        in: "query"
        description: "To request entityList data or not (example: 0 or 1)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Complex"
      security:
      - bearerAuth: []
  /Group/List:
    get:
      tags:
      - "Group"
      summary: "Get group IDs"
      description: ""
      operationId: "GetGroupList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "dateModified"
        in: "query"
        description: "Only return group IDs where a change was made after the given date (example: 20220101 -> yyyyMMdd)"
        required: true
        type: "string"
        format: "date"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "integer"
              format: "int32"
      security:
      - bearerAuth: []
  /Group/Range:
    get:
      tags:
      - "Group"
      summary: "Get group data in range (restricted to 100 records/request)"
      description: ""
      operationId: "GetGroupListRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "query"
        description: "range of IDs (example: 1,2,3,4,5)"
        required: true
        type: "string"
      - name: "adres"
        in: "query"
        description: "To request adres data or not (example: 0 or 1)"
        required: true
        type: "string"
      - name: "entityList"
        in: "query"
        description: "To request entityList data or not (example: 0 or 1)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Group"
      security:
      - bearerAuth: []
  /PandStatusCode/List:
    get:
      tags:
      - "PandStatus Code"
      summary: "Get all possible pand status IDs"
      description: ""
      operationId: "GetAttributeList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "integer"
              format: "int32"
      security:
      - bearerAuth: []
  /PandStatusCode/Range:
    get:
      tags:
      - "PandStatus Code"
      summary: "Get pand status code data in range (unrestricted amount of data records/request)"
      description: ""
      operationId: "GetAttributeRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "query"
        description: "range of IDs (example 1,2,3,4,5)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PandStatusCode"
      security:
      - bearerAuth: []
  /AttributeCode/List:
    get:
      tags:
      - "Attribute Code"
      summary: "Get all possible attribute code IDs"
      description: ""
      operationId: "GetAttributeCodeList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "integer"
              format: "int32"
      security:
      - bearerAuth: []
  /AttributeCode/Range:
    get:
      tags:
      - "Attribute Code"
      summary: "Get attribute code data in range (unrestricted amount of data records/request)"
      description: ""
      operationId: "GetAttributeCodeRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "query"
        description: "range of IDs (example 1,2,3,4,5)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/AttributeCode"
      security:
      - bearerAuth: []
securityDefinitions:
  bearerAuth:
    type: "apiKey"
    name: "bearer"
    in: "header"
definitions:
  Entity:
    type: "object"
    properties:
      entityID:
        type: "integer"
        format: "int32"
      number:
        type: "string"
      countrycode:
        type: "string"
      postalcode:
        type: "string"
      county:
        type: "string"
      street:
        type: "string"
      housenumber:
        type: "string"
      boxnumber:
        type: "string"
      complexcode:
        type: "string"
      structure:
        type: "string"
      lease:
        type: "string"
      status:
        type: "string"
      attributeList:
        type: "array"
        items:
          properties:
            attributeID:
              type: "integer"
              format: "int32"
            attributeCodeID:
              type: "integer"
              format: "int32"
            datefrom:
              type: "string"
              format: "datetime"
            dateuntil:
              type: "string"
              format: "datetime"
            value:
              type: "string"
  Complex:
    type: "object"
    properties:
      complexID:
        type: "integer"
        format: "int32"
      code:
        type: "string"
      description:
        type: "string"
      countrycode:
        type: "string"
      postalcode:
        type: "string"
      county:
        type: "string"
      street:
        type: "string"
      housenumber:
        type: "string"
      boxnumber:
        type: "string"
      entityIDList:
        type: "array"
        items:
          type: "integer"
          format: "int32"
  Group:
    type: "object"
    properties:
      groupID:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      description:
        type: "string"
      countrycode:
        type: "string"
      postalcode:
        type: "string"
      county:
        type: "string"
      street:
        type: "string"
      housenumber:
        type: "string"
      boxnumber:
        type: "string"
      entityIDList:
        type: "array"
        items:
          type: "integer"
          format: "int32"
  PandStatusCode:
    type: "object"
    properties:
      pandStatusCodeID:
        type: "integer"
        format: "int32"
      code:
        type: "string"
      description:
        type: "string"
  AttributeCode:
    type: "object"
    properties:
      attributeCodeID:
        type: "integer"
        format: "int32"
      code:
        type: "string"
      description:
        type: "string"
  Attribute:
    type: "object"
    properties:
      attributeID:
        type: "integer"
        format: "int32"
      attributeCodeID:
        type: "integer"
        format: "int32"
      datefrom:
        type: "string"
        format: "datetime"
      dateuntil:
        type: "string"
        format: "datetime"
      value:
        type: "string"
