swagger: "2.0"
info:
  description: "GashNetPlus REST API"
  version: "1.0.0"
  title: "Swagger GashNetPlus"
  contact:
    email: "helpdesk@gashnetplus.be"
basePath: "/v2"
schemes:
- "https"
paths:
  /Entity/List/:
    get:
      tags:
      - "Entity"
      summary: "Get all possible entity IDs"
      description: ""
      operationId: "GetEntityList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Entity"
      security:
      - api_key: []
  /Entity/List/{range}:
    get:
      tags:
      - "Entity"
      summary: "Get entity data in range"
      description: ""
      operationId: "GetEntityListRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "path"
        description: "range of IDs (example 1-10)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Entity"
      security:
      - api_key: []
  /Entity/{ID}:
    get:
      tags:
      - "Entity"
      summary: "Get entity data"
      description: ""
      operationId: "GetEntity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ID"
        in: "path"
        description: "ID of entity to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Entity"
      security:
      - api_key: []
  /Complex/List/:
    get:
      tags:
      - "Complex"
      summary: "Get all possible complex IDs"
      description: ""
      operationId: "GetComplexList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Complex"
      security:
      - api_key: []
  /Complex/List/{range}:
    get:
      tags:
      - "Complex"
      summary: "Get complex data in range"
      description: ""
      operationId: "GetComplexListRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "path"
        description: "range of IDs (example 1-10)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Complex"
      security:
      - api_key: []
  /Complex/{ID}:
    get:
      tags:
      - "Complex"
      summary: "Get complex data"
      description: ""
      operationId: "GetComplex"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ID"
        in: "path"
        description: "ID of complex to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Complex"
      security:
      - api_key: []
  /Group/List/:
    get:
      tags:
      - "Group"
      summary: "Get all possible group IDs"
      description: ""
      operationId: "GetGroupList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Group"
      security:
      - api_key: []
  /Group/List/{range}:
    get:
      tags:
      - "Group"
      summary: "Get group data in range"
      description: ""
      operationId: "GetGroupListRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "path"
        description: "range of IDs (example 1-10)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Group"
      security:
      - api_key: []
  /Group/{ID}:
    get:
      tags:
      - "Group"
      summary: "Get group data"
      description: ""
      operationId: "GetGroup"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ID"
        in: "path"
        description: "ID of complex to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Group"
      security:
      - api_key: []
  /Attribute/List/:
    get:
      tags:
      - "Attribute"
      summary: "Get all possible attribute IDs"
      description: ""
      operationId: "GetAttributeList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Attribute"
      security:
      - api_key: []
  /Attribute/List/{range}:
    get:
      tags:
      - "Attribute"
      summary: "Get attribute data in range"
      description: ""
      operationId: "GetAttributeListRange"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "range"
        in: "path"
        description: "range of IDs (example 1-10)"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Attribute"
      security:
      - api_key: []
  /Attribute/{ID}:
    get:
      tags:
      - "Attribute"
      summary: "Get attribute data"
      description: ""
      operationId: "GetAttribute"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ID"
        in: "path"
        description: "ID of complex to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Attribute"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Entity:
    type: "object"
    properties:
      entityID:
        type: "integer"
        format: "int32"
      number:
        type: "string"
      countrycode:
        type: "string"
      postalcode:
        type: "string"
      county:
        type: "string"
      street:
        type: "string"
      housenumber:
        type: "string"
      boxnumber:
        type: "string"
      complexcode:
        type: "string"
      structure:
        type: "string"
      system:
        type: "string"
      attributeList:
        type: "array"
        items:
          properties:
            attributecode:
              type: "string"
            datefrom:
              type: "string"
              format: "datetime"
            dateuntil:
              type: "string"
              format: "datetime"
            value:
              type: "string"
  Complex:
    type: "object"
    properties:
      complexID:
        type: "integer"
        format: "int32"
      code:
        type: "string"
      description:
        type: "string"
      countrycode:
        type: "string"
      postalcode:
        type: "string"
      county:
        type: "string"
      street:
        type: "string"
      housenumber:
        type: "string"
      boxnumber:
        type: "string"
      entityIDList:
        type: "array"
        items:
          type: "integer"
          format: "int32"
  Group:
    type: "object"
    properties:
      groupID:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      description:
        type: "string"
      countrycode:
        type: "string"
      postalcode:
        type: "string"
      county:
        type: "string"
      street:
        type: "string"
      housenumber:
        type: "string"
      boxnumber:
        type: "string"
      entityIDList:
        type: "array"
        items:
          type: "integer"
          format: "int32"
  Attribute:
    type: "object"
    properties:
      attributeID:
        type: "integer"
        format: "int32"
      code:
        type: "string"
      description:
        type: "string"
